enum {RAVENSWOOD, FOREST, CAVES};
enum {MIRROR, BELL, HEALINGSALVE, LONGSWORD, AXE, DAGGER, MACE, MEDIUMSHIELD, LEATHERARMOR,CHAINMAIL, PLATEMAIL,FULLPLATEMAIL,STAKE};
enum {HAND, ARMOR, HELMET, WEAPON, SHIELD, BOOTS, GIRDLE, GAUNTLETS, DUMMY};
enum {FIGHTER, CLERIC, MAGE, THIEF};